local icons = {
  
  -- Forced icon
  -- those icons are set customly

  ["Falling damage"] = "CRB_ActionBarFrameSprites:sprResourceBar_Sprint_RunIconRed",

  -- stalker

  ["Amplification Spike"] = "ClientSprites:Icon_SkillStalker_Amplifide_Spike",
  ["Analyze Weakness"] = "ClientSprites:Icon_SkillStalker_Analyze_Weakness",
  Bloodthirst = "ClientSprites:Icon_SkillStalker_Blood_Thirst",
  Clone = "Icon_SkillStalker_Clone",
  Collapse = "Icon_SkillShadow_UI_stlkr_ragingslash",
  ["Concussive Kicks"] = "ClientSprites:Icon_SkillStalker_Concussive_Kicks",
  Cripple = "ClientSprites:Icon_SkillStalker_Cripple",
  Decimate = "ClientSprites:Icon_SkillStalker_Destructive_Sweep",
  ["False Retreat"] = "Icon_SkillShadow_UI_stlkr_shadowdash",
  Frenzy = "Icon_SkillShadow_UI_stlkr_shredarmor",
  Impale = "Icon_SkillShadow_UI_stlkr_tacticalthrust",
  ["Nano Dart"] = "ClientSprites:Icon_SkillStalker_Nano_Dart",
  ["Nano Field"] = "ClientSprites:Icon_SkillStalker_Nano_Field",
  ["Nano Virus"] = "ClientSprites:Icon_SkillStalker_Nano_Virus",
  Neutralize = "ClientSprites:Icon_SkillStalker_Neutralize",
  Phlebotomize = "ClientSprites:Icon_SkillStalker_Phlebotomizing_Missile",
  Pounce = "Icon_SkillShadow_UI_stlkr_pounce",
  Preparation = "ClientSprites:Icon_SkillStalker_Preparation",
  Punish = "ClientSprites:Icon_SkillStalker_Punish",
  ["Razor Disk"] = "ClientSprites:Icon_SkillStalker_Razor_Disk",
  ["Razor Storm"] = "Icon_SkillShadow_UI_SM_envelop",
  Reaver = "ClientSprites:Icon_SkillStalker_Reaver",
  Ruin = "Icon_SkillStalker_overload",
  Shred = "Icon_SkillShadow_UI_sm_rip",
  Stagger = "Icon_SkillShadow_UI_stlkr_staggeringthrust",
  Steadfast = "Icon_SkillStalker_Steadfast",
  ["Stim Drone"] = "ClientSprites:Icon_SkillStalker_Augment_Drone",
  ["Tactical Retreat"] = "Icon_SkillShadow_UI_stlkr_emergencystealth",
  ["Tether Mine"] = "Icon_SkillStalker_Tether_Mine",
  Whiplash = "ClientSprites:Icon_SkillStalker_Whiplash",


  -- spellslinger

  Affinity = "Icon_SkillSpellslinger_affinity",
  ["Arcane Missiles"] = "Icon_SkillSpellslinger_magic_missile",
  ["Arcane Shock"] = "Icon_SkillSpellslinger_arcane_shock",
  Assassinate = "Icon_SkillSpellslinger_assassinate",
  ["Astral Infusion"] = "Icon_SkillSpellslinger_arcane_infusion",
  ["Charged Shot"] = "Icon_SkillSpellslinger_charged_shot",
  Chill = "Icon_SkillSpellslinger_cone_of_frost",
  ["Dual Fire"] = "Icon_SkillSpellslinger_dual_fire",
  ["Flame Burst"] = "Icon_SkillSpellslinger_flame_burst",
  ["Flash Freeze"] = "Icon_SkillSpellslinger_frozen_bolt",
  Gate = "Icon_SkillSpellslinger_gate",
  ["Gather Focus"] = "Icon_SkillSpellslinger_gather_mana",
  ["Healing Salve"] = "Icon_SkillSpellslinger_healing_salve",
  ["Healing Torrent"] = "Icon_SkillSpellslinger_healing_torrent",
  Ignite = "Icon_SkillSpellslinger_ignite",
  ["Phase Shift"] = "Icon_SkillSpellslinger_phase_shift",
  Purify = "Icon_SkillSpellslinger_purify",
  ["Quick Draw"] = "IconSprites:Icon_SkillSpellslinger_mobile_fire",
  ["Rapid Fire"] = "Icon_SkillSpellslinger_rapid_fire",
  ["Regenerative Pulse"] = "Icon_SkillSpellslinger_regenerative_pulse",
  ["Runes of Protection"] = "Icon_SkillSpellslinger_distortion",
  ["Runic Healing"] = "Icon_SkillSpellslinger_runic_healing",
  ["Spatial Shift"] = "Icon_SkillSpellslinger_spatial_shift",
  Sustain = "Icon_SkillSpellslinger_sustain",
  ["True Shot"] = "Icon_SkillSpellslinger_Trueshot",
  ["Vitality Burst"] = "Icon_SkillSpellslinger_vitality_burst",
  ["Void Pact"] = "Icon_SkillSpellslinger_void_pact",
  ["Void Slip"] = "Icon_SkillSpellslinger_void_slip",
  Voidspring = "Icon_SkillSpellslinger_call_the_void",
  ["Wild Barrage"] = "Icon_SkillSpellslinger_wild_barrage",


  -- Esper

  ["Blade Dance"] = "ClientSprites:Icon_SkillEsper_Blade_Dance",
  Bolster = "Icon_SkillMind_UI_espr_bolster",
  Catharsis = "ClientSprites:Icon_SkillEsper_Awaken_Alt",
  ["Concentrated Blade"] = "Icon_SkillMind_UI_espr_bldstrm",
  Crush = "Icon_SkillMind_UI_espr_crush",
  ["Fade Out"] = "ClientSprites:Icon_SkillEsper_Fade_Out",
  Fixation = "Icon_SkillShadow_UI_SM_eye",
  Geist = "ClientSprites:Icon_SkillEsper_Geist",
  Haunt = "Icon_SkillMind_UI_espr_phbmve",
  ["Illusionary Blades"] = "ClientSprites:Icon_SkillEsper_Illusionary_Blades",
  Incapacitate = "ClientSprites:Icon_SkillEsper_Sudden_Quiet",
  Meditate = "Icon_SkillMind_UI_espr_mdt",
  ["Mending Banner"] = "Icon_SkillMind_UI_espr_moverb",
  ["Mental Boon"] = "ClientSprites:Icon_SkillEsper_Mental_Boon",
  ["Mind Burst"] = "Icon_SkillMind_UI_espr_mndstb",
  ["Mind Over Body"] = "ClientSprites:Icon_SkillEsper_Mind_Over_Body",
  Mirage = "ClientSprites:Icon_SkillEsper_Mirage",
  ["Phantasmal Armor"] = "Icon_SkillMind_UI_espr_phnstmlarmor",
  ["Projected Spirit"] = "ClientSprites:Icon_SkillEsper_Projected_Spirit",
  ["Psychic Frenzy"] = "ClientSprites:Icon_SkillEsper_Spectral_Frenzy",
  ["Pyrokinetic Flame"] = "ClientSprites:Icon_SkillEsper_Dislodge_Essence",
  Reap = "Icon_SkillShadow_UI_SM_rprrsh",
  Restraint = "Icon_SkillMisc_UI_misc_vlnrbl",
  Reverie = "Icon_SkillMisc_UI_m_flsh",
  Shockwave = "Icon_SkillMind_UI_espr_shockwave",
  Soothe = "ClientSprites:Icon_SkillEsper_Soothe",
  ["Spectral Swarm"] = "Icon_SkillShadow_UI_SM_undrwrlddrms",
  ["Telekinetic Storm"] = "Icon_SkillEnergy_UI_srcr_elctrcshck",
  ["Telekinetic Strike"] = "Icon_SkillMisc_UI_srcr_enhncesns",
  Warden = "ClientSprites:Icon_SkillEsper_Warden",

  
  -- warrior

  ["Atomic Spear"] = "Icon_SkillWarrior_Atomic_Spear",
  ["Atomic Surge"] = "ClientSprites:Icon_SkillWarrior_Plasma_Pulse",
  ["Augmented Blade"] = "Icon_SkillMisc_UI_m_amplfydmg",
  ["Bolstering Strike"] = "Icon_SkillMisc_UI_wr_dfgrp",
  ["Breaching Strikes"] = "Icon_SkillPhysical_UI_wr_clv",
  ["Bum Rush"] = "Icon_SkillNature_UI_srcr_wndwlk",
  ["Defense Grid"] = "Icon_SkillWarrior_Defense_Grid",
  ["Emergency Reserves"] = "Icon_SkillWarrior_Emergency_Reserves",
  Expulsion = "ClientSprites:Icon_SkillWarrior_Explusion",
  ["Flash Bang"] = "Icon_SkillPhysical_UI_wr_grenade",
  Grapple = "Icon_SkillPhysical_UI_wr_whip",
  Jolt = "Icon_SkillWarrior_Cannon_Volley",
  Kick = "Icon_SkillPhysical_UI_wr_punt",
  Leap = "Icon_SkillPhysical_UI_wr_leap",
  ["Menacing Strike"] = "ClientSprites:Icon_SkillWarrior_Guarded_Strikes",
  ["Plasma Blast"] = "ClientSprites:Icon_SkillWarrior_Plasma_Blast",
  ["Plasma Wall"] = "ClientSprites:Icon_SkillWarrior_Plasma_Wall",
  ["Polarity Field"] = "ClientSprites:Icon_SkillWarrior_Polarity_Field",
  ["Power Link"] = "ClientSprites:Icon_SkillWarrior_Power_Link",
  Rampage = "Icon_SkillMisc_UI_wr_offgrp",
  ["Relentless Strikes"] = "Icon_SkillPhysical_UI_wr_lng",
  Ripsaw = "Icon_SkillPhysical_UI_wr_saw",
  ["Savage Strike"] = "Icon_SkillPhysical_UI_wr_cntrsrk",
  Sentinel = "ClientSprites:Icon_SkillMisc_UI_espr_tlkntcshld",
  ["Shield Burst"] = "ClientSprites:Icon_SkillWarrior_Shield_Burst",
  Smackdown = "Icon_SkillPhysical_UI_wr_slap",
  ["Tether Bolt"] = "ClientSprites:Icon_SkillWarrior_Tether_Anchor",
  Tremor = "ClientSprites:Icon_SkillWarrior_Tremor_Strike",
  ["Unstoppable Force"] = "ClientSprites:Icon_SkillWarrior_Unstoppable_Force",
  Whirlwind = "Icon_SkillPhysical_UI_wr_wrlwnd",


  -- Engi

  Artillerybot = "Icon_SkillEngineer_Pet_Ability_Barrage",
  ["Bio Shell"] = "Icon_SkillEngineer_BioShell",
  ["Bolt Caster"] = "Icon_SkillEngineer_Bolt_Caster",
  Bruiserbot = "Icon_SkillEngineer_Bruiser_Bot",
  ["Code Red"] = "Icon_SkillEngineer_Code_Red",
  Diminisherbot = "Icon_SkillEngineer_Diminisher_Bot",
  ["Disruptive Module"] = "Icon_SkillEngineer_Disruptive_Mod",
  Electrocute = "Icon_SkillEngineer_Electrocute",
  ["Energy Auger"] = "Icon_SkillEngineer_Energy_Trail",
  Feedback = "Icon_SkillEngineer_Feedback",
  ["Flak Cannon"] = "Icon_SkillEngineer_Flak_Cannon",
  ["Hyper Wave"] = "Icon_SkillEngineer_Hyper_Wave",
  ["Mortar Strike"] = "Icon_SkillEngineer_Mortar_Strike",
  ["Obstruct Vision"] = "ClientSprites:Icon_SkillEngineer_Shock_Wave",
  ["Particle Ejector"] = "Icon_SkillEngineer_Particule_Ejector",
  ["Personal Defense Unit"] = "ClientSprites:Icon_SkillEngineer_Personal_Defense_Unit",
  ["Pulse Blast"] = "ClientSprites:Icon_SkillEngineer_Pulse_Blast",
  ["Quick Burst"] = "ClientSprites:Icon_SkillEngineer_Quick_Burst",
  ["Recursive Matrix"] = "ClientSprites:Icon_SkillEngineer_Recursive_Matrix",
  Repairbot = "ClientSprites:Icon_SkillEngineer_Repair_Bot",
  Ricochet = "ClientSprites:Icon_SkillEngineer_Ricochet",
  ["Shatter Impairment"] = "ClientSprites:Icon_SkillEngineer_Shatter_Impairment",
  ["Shock Pulse"] = "ClientSprites:Icon_SkillEngineer_Shock_Pulse",
  ["Target Acquisition"] = "ClientSprites:Icon_SkillEngineer_Target_Acquistion",
  Thresher = "ClientSprites:Icon_SkillEngineer_Thresher",
  ["Unstable Anomaly"] = "Icon_SkillEngineer_Anomaly_Launcher",
  ["Unsteady Miasma"] = "Icon_SkillEngineer_Give_Em_Gas",
  ["Urgent Withdrawal"] = "ClientSprites:Icon_SkillEngineer_Urgent_Withdrawal",
  ["Volatile Injection"] = "ClientSprites:Icon_SkillEngineer_Volatile_Injection",
  Zap = "ClientSprites:Icon_SkillEngineer_Zap",


  -- Medic

  Annihilation = "ClientSprites:Icon_SkillMedic_annihilation",
  Antidote = "ClientSprites:Icon_SkillMedic_suture",
  Atomize = "ClientSprites:Icon_SkillMedic_atomize",
  Barrier = "ClientSprites:Icon_SkillMedic_Barrier",
  Calm = "ClientSprites:Icon_SkillMedic_Calm",
  Collider = "ClientSprites:Icon_SkillMedic_particlecollider",
  ["Crisis Wave"] = "ClientSprites:Icon_SkillMedic_fieldsurgeon",
  Dematerialize = "Icon_SkillEnergy_UI_srcr_shckcntrp",
  ["Devastator Probes"] = "ClientSprites:Icon_SkillMedic_devastatorprobes1",
  Discharge = "ClientSprites:Icon_SkillMedic_discharge",
  ["Dual Shock"] = "ClientSprites:Icon_SkillMedic_paddleshock",
  Emission = "ClientSprites:Icon_SkillMedic_Emission",
  ["Empowering Probes"] = "ClientSprites:Icon_SkillMedic_empowerprobe",
  Extricate = "ClientSprites:Icon_SkillMedic_extricate",
  ["Field Probes"] = "ClientSprites:Icon_SkillMedic_fieldprobes1",
  Fissure = "ClientSprites:Icon_SkillMedic_Fissure",
  Flash = "ClientSprites:Icon_SkillMedic_healingnova",
  ["Gamma Rays"] = "ClientSprites:Icon_SkillMedic_gammarays",
  ["Magnetic Lockdown"] = "ClientSprites:Icon_SkillMedic_magneticlockdown",
  ["Mending Probes"] = "ClientSprites:Icon_SkillMedic_repairprobes1",
  Nullifier = "ClientSprites:Icon_SkillMedic_nullifyfield",
  ["Paralytic Surge"] = "ClientSprites:Icon_SkillMedic_paralyticsurge",
  ["Protection Probes"] = "ClientSprites:Icon_SkillMedic_protectionprobe1",
  ["Quantum Cascade"] = "ClientSprites:Icon_SkillMedic_quantumcascade",
  Recharge = "ClientSprites:Icon_SkillMedic_recharge",
  Rejuvenator = "ClientSprites:Icon_SkillMedic_repairstation",
  Restrictor = "ClientSprites:Icon_SkillMedic_restraintgrind",
  ["Shield Surge"] = "ClientSprites:Icon_SkillMedic_sheildsurge",
  Triage = "ClientSprites:Icon_SkillMedic_MedicIconTreatWounds",
  Urgency = "ClientSprites:Icon_SkillMedic_urgency"

}


Apollo.RegisterPackage(icons, "DarkMeter:Icons", 1, {})